### ISSUE TITLE
Feature Request: make load-pod proxy aware

### ISSUE THREAD

**Issue by bennyandresen** [babashka/pods#27]
Not sure if this repository or the pod-registry is the right place for this feature request.

When inside a corporate proxy environment, the automatic download from the pod-registry fails.
I don't think `http_proxy`, `https_proxy` are anything more than a convention, but it would be nice if load-pod respected these.

**Comment by borkdude** [comment]
@bennyandresen Good point, we can do that. This logic is also in https://github.com/borkdude/deps.clj. Feel free to port it to (this) repo and submit a PR.

**Comment by Charlynux** [comment]
For the record,

I successfully hit my proxy with 2 differents methods: 
- `bb -Djava.net.useSystemProxies=true`
- `bb -Dhttp.proxyHost=myproxy.net -Dhttp.proxyPort=1234 -Dhttps.proxyHost=myproxy.net -Dhttps.proxyPort=1234`

(Sadly, I got a 407 since my proxy requires authentication.)

**Comment by borkdude** [comment]
Nice! Is there anything we should do about the 407 or is this expected behavior?

**Comment by Charlynux** [comment]
From my googling, Java doesn't offer a property for proxy credentials, so I suppose using an authenticated proxy will require a specific implementation.

**Comment by Charlynux** [comment]
I work a bit on the subject and successfully download pods behind a corporate proxy.

# The problem

First to reduce the "search field", I clone the `download` function from the pods resolver.

```clojure
(import '[java.net URL HttpURLConnection])
(defn download [url]
  (let [source (URL. url)
      conn ^HttpURLConnection (.openConnection ^URL source)]
  (.setInstanceFollowRedirects conn true)
  (.connect conn)
  (with-open [is (.getInputStream conn)]
    (slurp is))))

(download "http://www.google.com") ;; 407 - Proxy Authentication Required
(download "https://www.google.com") ;; 407 - Proxy Authentication Required
```

As expected, I got 407 errors on each download.

# Implements "Proxy Authentication"

On [StackOverflow](https://stackoverflow.com/questions/1626549/authenticated-http-proxy-with-java), I found this solution.

```clojure
(java.net.Authenticator/setDefault
 (proxy [java.net.Authenticator] []
        (getPasswordAuthentication []
          (prn "Authentication...")
          (java.net.PasswordAuthentication.
           "user"
           (.toCharArray "password")))))
```

Retry `(download "https://www.google.com")` got a 407 again. I notice that my `prn` message doesn't show up.

Retry `(download "http://www.google.com")`, "Authentication..." appears and I got HTML body.
Try `(download "https://www.google.com")` once again and I got HTML body (without the debug message) !

From there, I could `pods/load-pod` without any problem.
I bet there is some credentials caching in the process.

# Conclusion for babashka

I can't see a way for babashka to help with this.

*So, if you're behind a corporate proxy and want to use Babashka Pods, you will need to use `Authenticator/setDefault` and open a connection  to an http URL, as a preliminary workaround.*

# (Partial) reproduction environment

To work on this at home, I used `fake-corp-proxy` with Basic Authentication.

```shell
npx fake-corp-proxy --port 8080 --basic
```

I don't take time to make `--https` works, so I got SSL errors when proxy authentication succeed. Not a problem for me, I just want to distinguish when proxy let me pass.
