### ISSUE TITLE
Force flag not working on Windows

### ISSUE THREAD

**Issue by vrikselzi** [babashka/pods#37]
In Windows, when calling `load-pod`, the pod always gets downloaded regardless of setting the `:force` flag to `false`. In macOS, the flag works as intended.

For example:
```
(pods/load-pod 'org.babashka/buddy "0.0.1" {:force false})
```
Will always show after executing:
```
Downloading pod org.babashka/buddy (0.0.1)
Successfully installed pod org.babashka/buddy (0.0.1)
```
Even though the pod's files (`pod-babashka-buddy.exe` and `manifest.edn`) are already there in `.babashka\pods\repository\org.babashka\buddy\0.0.1` in the user's home directory.

**Comment by borkdude** [comment]
@vrikselzi Hmm, it seems to be a specific issue to this pod. E.g. I don't have this problem with `borkdude/clj-kondo "2021.02.13"`. I'll look into it.

**Comment by borkdude** [comment]
@vrikselzi Fixed it for the buddy pod. If this happens for more pods, then I should change the manifest. I'll make a better fix in babashka itself. The issue is that there is a check for the executable but without the `.exe` extension.

**Comment by borkdude** [comment]
@vrikselzi It's best to throw away the `.babashka\pods\repository\org.babashka\buddy` and then try again.
