### ISSUE TITLE
working with babashka pods in Clojure REPL

### ISSUE THREAD

**Issue by takaczapka** [babashka/pods#42]
Hello, 

It looks like having babashka pods loading in code prevents me from loading it correctly to clojure REPL (I use nRepl via Cursive). So I can't work with the code interactively nor run tests. 

This is the sample code snippet
```
(ns sample-ns
(:require [babashka.pods :as pods]))

(pods/load-pod 'org.babashka/postgresql "0.0.7")
(require '[pod.babashka.postgresql :as pg])
```

When loading a namespace or running at test, REPL moaned with:
```
Syntax error (FileNotFoundException) compiling at (src/employee.clj:1:1).
Could not locate babashka/pods__init.class, babashka/pods.clj or babashka/pods.cljc on classpath.
```
 
So I've added this to deps.edn
```babashka/babashka.pods              {:mvn/version "0.0.1"}```

Another try and this happened:
```
Syntax error (FileNotFoundException) compiling at (babashka/pods/impl.clj:1:1).
Could not locate cognitect/transit__init.class, cognitect/transit.clj or cognitect/transit.cljc on classpath.
```

So I've added following to deps.edn:
```           com.cognitect/transit-clj           {:mvn/version "1.0.324"}```

Which made me arrive to this problem 
```
Syntax error compiling at (REPL:18:3).
No such var: babashka.pods/add-transit-read-handler!
```

And I'm stuck and I'm not sure how to bite it.

Hence the question: how to use of babashka pods in REPL driven setup? 

Thanks,
Maciej

**Comment by borkdude** [comment]
@takaczapka Since you're already using `deps.edn`, I recommend using this library as a git dependency with the latest SHA. The most recent postgres pod assumes a commit which isn't in 0.0.1.

**Comment by takaczapka** [comment]
Thanks, great suggestion.
