### ISSUE TITLE
Fix (benign) socket closed error message

### ISSUE THREAD

**Issue by borkdude** [babashka/pods#49]
With this repo, when you repeatedly execute `bb bar`, then you see a socket closed exception being printed, which is probably benign, but we should fix this.

https://github.com/sheluchin/bb-spire-pod-repro

cc @lispyclouds @cap10morgan

**Comment by lispyclouds** [comment]
What's a recommended fix? A more graceful failure message?

**Comment by borkdude** [comment]
@lispyclouds Before fixing we should first diagnose the problem, but I expect that we try to read from a closed socket, perhaps after the pod has already been shut down.
