### ISSUE TITLE
Allow overriding os.name & os.arch when caching pods

### ISSUE THREAD

**Issue by cap10morgan** [babashka/pods#52]
**Is your feature request related to a problem? Please describe.**
Sometimes I need to download and cache pod binaries for the OS & arch I'm deploying to, not the one I'm building on.

**Describe the solution you'd like**
I need to override the values of the `os.name` and `os.arch` properties when Babashka decides which pod binaries to download in the `prepare` step.

**Describe alternatives you've considered**
I tried setting the `os.name` and `os.arch` properties directly, but the JVM seems to think it's running on that OS/arch then and chooses the wrong native interfaces for e.g. socket communications.

**Additional context**
I'm thinking a simple pair of env vars could work. When set, they'll take the place of the `os.name` and `os.arch` values. Something like `OS_NAME` and `OS_ARCH`?

**Comment by borkdude** [comment]
@cap10morgan In addition to this, I think we should store the pod binaries in a directory structure that has the os + arch:

```
.babashka/pods/repository/macos/amd64/clj-kondo/....
```

for example. 

This way, we don't get conflicts when setting these env vars. 

I think the env vars should have a more general name to not cause weird behavior with other tools, e.g.  `BABASHKA_POD_OS_NAME` or so.

**Comment by cap10morgan** [comment]
@borkdude Do we need backwards-compatibility with the old local pod paths that don't include the platform dirs? If so, should we move them to the new location when we find pods there?

**Comment by borkdude** [comment]
No need for backwards-compatibility as the pod will be downloaded another time, right?

**Comment by cap10morgan** [comment]
> No need for backwards-compatibility as the pod will be downloaded another time, right?

Yep!

**Comment by cap10morgan** [comment]
I did `BABASHKA_PODS_OS_*` so it matches the prefix for e.g. `BABASHKA_PODS_DIR`.

And I made the new paths `pod-name/version/os/arch` so that the `manifest.edn` could still go in `pod-name/version` and the os/arch dirs would be subdirs of that.

Let me know if you'd like me to change any of that.

**Comment by borkdude** [comment]
Sounds great! I'll take another look at this tomorrow.

**Comment by borkdude** [comment]
@cap10morgan Sorry, had to revert pr #53 because bb tests were failing.

https://app.circleci.com/pipelines/github/babashka/babashka/6037/workflows/e89e4d1d-1c93-4a91-8b0d-5f816bd51b13/jobs/31039

Will accept another PR, but will first test it with bb before merging.

**Comment by cap10morgan** [comment]
Think I found the issue. New PR coming shortly.

**Comment by borkdude** [comment]
OK, test running in `pods-issue-52` branch on bb CI.

**Comment by borkdude** [comment]
That worked, thanks
