### ISSUE TITLE
On JVM, requiring pods that have clashing names with `clojure.core` will show warning, even if it doesn't use `:refer :all`

### ISSUE THREAD

**Issue by keychera** [babashka/pods#65]
minimal reproducible example

`src/pods-test.clj`
```clojure
(ns pods-test (:require clojure.zip [babashka.pods :as pods]))
(pods/load-pod 'retrogradeorbit/bootleg "0.1.9")
(require '[pod.retrogradeorbit.hickory.select :as s])
(defn -main [& _] (println "hello"))
```
then run
```
clojure -Sdeps '{:deps {org.clojure/clojure {:mvn/version "1.11.1"} babashka/babashka.pods {:mvn/version "0.2.0"}}}' -M -m pods-test
```

it would print
```
WARNING: class already refers to: #'clojure.core/class in namespace: pod.retrogradeorbit.hickory.select, being replaced by: #'pod.retrogradeorbit.hickory.select/class
WARNING: and already refers to: #'clojure.core/and in namespace: pod.retrogradeorbit.hickory.select, being replaced by: #'pod.retrogradeorbit.hickory.select/and
WARNING: or already refers to: #'clojure.core/or in namespace: pod.retrogradeorbit.hickory.select, being replaced by: #'pod.retrogradeorbit.hickory.select/or
WARNING: not already refers to: #'clojure.core/not in namespace: pod.retrogradeorbit.hickory.select, being replaced by: #'pod.retrogradeorbit.hickory.select/not
hello
```

**Comment by borkdude** [comment]
I think the solution is to change `*ns*` to `name` here:

https://github.com/babashka/pods/blob/75c2216649bf5caf3ae41e7b8fc202e45b090ea9/src/babashka/pods/jvm.clj#L18

**Comment by keychera** [comment]
@borkdude 
I just tried that change locally but the warning still shows up, and I tried printing every name that pass through the `doseq` and it seems `pod.retrogradeorbit.hickory.select` enters the `string?` branch of the `cond`

**Comment by borkdude** [comment]
There are some other places where intern is used that may need this change?

**Comment by keychera** [comment]
I only found three `intern` but I think the changes won't affect this particular namespace since it use `load-string` instead of `intern`
``` clojure
(cond
  (ifn? v)
  (do
    (ns-unmap name var-sym)
    (intern name var-sym v))
  (string? v)
  (load-string v)) ;; <-- pod.retrogradeorbit.hickory.select is loaded here
```

**Comment by keychera** [comment]
ah, it seems `(ns-unmap name var-sym)` before load-string works! but I feel like I don't quite understand the code fully to determine whether this change is safe or not
@borkdude 

but I will try making PR and move the discussion there

**Comment by keychera** [comment]
On second thought, I'm holding back the PR for now @borkdude 
I just ran the test and a lot was breaking. I'm quite stumped on why since I don't understand it fully yet

the changes were
```clojure
(cond
  (ifn? v)
  (do
    (ns-unmap *ns* var-sym)
    (intern name var-sym v))
  (string? v)
  (do
    (ns-unmap name var-sym)
    (load-string v)))
```

**Comment by borkdude** [comment]
I'll take a look when I have some more time

**Comment by borkdude** [comment]
The fix looks OK to me, and I tried finding out why the tests are breaking but so far no luck. Will give it another go, a bit short on time today.

**Comment by borkdude** [comment]
OK, found a fix
